CREATE TABLE [ETL].[LoadConfig_NEW] (
    [LoadConfigID]                               INT            IDENTITY (1, 1) NOT NULL,
    [SourceSystemName]                           [sysname]      DEFAULT ('ARBITRARY') NOT NULL,
    [SourceServerName]                           [sysname]      DEFAULT (CONVERT([sysname],isnull(serverproperty('ServerName'),@@servername))) NOT NULL,
    [SourceDatabaseInstanceName]                 [sysname]      DEFAULT ('DEFAULT') NOT NULL,
    [SourceDatabaseName]                         [sysname]      DEFAULT (db_name()) NOT NULL,
    [SourceSchemaName]                           [sysname]      DEFAULT (schema_name()) NOT NULL,
    [SourceDataEntityName]                       [sysname]      NOT NULL,
    [SourceFullyQualifiedReference]              AS             (((((((([SourceServerName]+'.')+case when [SourceDatabaseInstanceName]='DEFAULT' then '' else '\'+[SourceDatabaseInstanceName] end)+'.')+[SourceDatabaseName])+'.')+[SourceSchemaName])+'.')+[SourceDataEntityName]),
    [SourceDataEntityType]                       [sysname]      DEFAULT ('TABLE') NOT NULL,
    [TargetSystemName]                           [sysname]      DEFAULT ('ARBITRARY') NOT NULL,
    [TargetServerName]                           [sysname]      DEFAULT (CONVERT([sysname],isnull(serverproperty('ServerName'),@@servername))) NOT NULL,
    [TargetDatabaseInstanceName]                 [sysname]      DEFAULT ('DEFAULT') NOT NULL,
    [TargetDatabaseName]                         [sysname]      DEFAULT (db_name()) NOT NULL,
    [TargetSchemaName]                           [sysname]      DEFAULT (schema_name()) NOT NULL,
    [TargetDataEntityName]                       [sysname]      NOT NULL,
    [TargetFullyQualifiedReference]              AS             (((((((([TargetServerName]+'.')+case when [TargetDatabaseInstanceName]='DEFAULT' then '' else '\'+[TargetDatabaseInstanceName] end)+'.')+[TargetDatabaseName])+'.')+[TargetSchemaName])+'.')+[TargetDataEntityName]),
    [TargetDataEntityType]                       [sysname]      DEFAULT ('TABLE') NOT NULL,
    [StaticFieldList]                            NVARCHAR (MAX) NULL,
    [IsDetermineFieldListAtRunTime]              BIT            DEFAULT ((0)) NOT NULL,
    [IsUpdateStaticFieldListAtRuntime]           BIT            DEFAULT ((0)) NOT NULL,
    [LoadType]                                   NVARCHAR (128) NULL,
    [IsUseExternalObjectIncremental]             BIT            DEFAULT ((0)) NOT NULL,
    [ExternalIncrementalFullyQualifiedReference] NVARCHAR (523) NULL,
    [IsUseCDC]                                   BIT            DEFAULT ((0)) NOT NULL,
    [CDCFullyQualifiedReference]                 NVARCHAR (523) NULL,
    [IsUseLinkedServer]                          BIT            DEFAULT ((0)) NOT NULL,
    [IsCheckMetaData]                            BIT            DEFAULT ((0)) NOT NULL,
    [IsCreateTargetIfNotExists]                  BIT            DEFAULT ((1)) NOT NULL,
    [IsDropAndRecreateTarget]                    BIT            DEFAULT ((0)) NOT NULL,
    [IsRecreatePrimaryKey]                       BIT            DEFAULT ((0)) NOT NULL,
    [PrimaryKeyField]                            NVARCHAR (MAX) NULL,
    [IsPrimaryKeyClustered]                      BIT            NULL,
    [IsRecreateIndex]                            BIT            DEFAULT ((0)) NOT NULL,
    [IsRecreateIdentity]                         BIT            DEFAULT ((0)) NOT NULL,
    [CreatedDT]                                  DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [UpdatedDT]                                  DATETIME2 (7)  NULL,
    [IsActive]                                   BIT            DEFAULT ((1)) NULL,
    CONSTRAINT [PK_ETL_LoadConfig] PRIMARY KEY CLUSTERED ([LoadConfigID] ASC)
);

